services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mydb:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=taipei_attractions
      - MYSQL_HOST=mydb
      - MYSQL_PORT=3306
      - MYSQL_USER=stella
      - MYSQL_PASSWORD=23322907
    ports:
      - "8001:8000"
    # volumes:
    #   - static_volume:/taipei-day-trip/app/static
    networks:
      - app-network
    restart: always
  mydb:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=taipei_attractions
      - MYSQL_ROOT_PASSWORD=23322907
      - MYSQL_USER=stella
      - MYSQL_PASSWORD=23322907
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "stella",
          "-p23322907",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./taipei_attractions.sql:/docker-entrypoint-initdb.d/taipei_attractions.sql
    restart: always
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      # - static_volume:/taipei-day-trip/app/static
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      # - type: bind
      #   source: ./.well-known
      #   target: /usr/share/nginx/html/.well-known
      # - type: bind
      #   source: ./ssl
      #   target: /taipei-day-trip/ssl
    depends_on:
      - app
    networks:
      - app-network
    restart: always
    command: [nginx-debug, "-g", "daemon off;"]
volumes:
  mysql_data:
    name: taipei-day-trip-db
  static_volume:
networks:
  app-network:
    name: taipei-day-trip-app-network
    driver: bridge
