version: "1"
services:
  app:
    image: stellayou/taipei-day-trip:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mydb
        # condition:service_healthy
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_HOST=mydb
      # - MYSQL_PORT=3306
      # - MYSQL_DATABASE=taipei_attractions
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=23322907
    ports:
      - "8001:8000"

  mydb:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_DATABASE: taipei_attractions
      # # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # MYSQL_USER: root
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_PASSWORD: 23322907
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_ROOT_PASSWORD: 23322907
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mydb"]
      interval: 30s
      timeout: 10s
      retries: 5
# Names our volume
volumes:
  my-db:
