services:
  app:
    image: stellayou/taipei-day-trip:${VERSION}
    build:
      args:
        VERSION: ${VERSION}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ACCESS_TOKEN_EXPIRE_DAYS: ${ACCESS_TOKEN_EXPIRE_DAYS:-7}
        ALGORITHM: ${ALGORITHM:-HS256}
        MERCHANT_ID: ${MERCHANT_ID}
        SECRET_KEY: ${SECRET_KEY}
        PARTNER_KEY: ${PARTNER_KEY}
        TAPPAY_SANDBOX_URL: ${TAPPAY_SANDBOX_URL}
      context: .
      dockerfile: Dockerfile
    depends_on:
      mydb:
        condition: service_healthy
    environment:
      - VERSION=${VERSION}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ACCESS_TOKEN_EXPIRE_DAYS=${ACCESS_TOKEN_EXPIRE_DAYS:-7}
      - ALGORITHM=${ALGORITHM:-HS256}
      - MERCHANT_ID=${MERCHANT_ID}
      - SECRET_KEY=${SECRET_KEY}
      - PARTNER_KEY=${PARTNER_KEY}
      - TAPPAY_SANDBOX_URL=${TAPPAY_SANDBOX_URL}
    ports:
      - "8001:8000"
    volumes:
      - static_volume:/taipei-day-trip/app/static
    networks:
      - app-network
    expose:
      - "8000"
  mydb:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m
      timeout: 10s
      retries: 10
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - static_volume:/taipei-day-trip/app/static
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.confＺ
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./.well-known
        target: /usr/share/nginx/html/.well-known
      - type: bind
        source: ./ssl
        target: /taipei-day-trip/ssl
    depends_on:
      - app
    networks:
      - app-network
    restart: always
    command: [nginx-debug, "-g", "daemon off;"]
volumes:
  my-db:
    name: taipei-day-trip-db
  static_volume:
networks:
  app-network:
    name: taipei-day-trip-app-network
    driver: bridge
