services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mydb:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=taipei_attractions
      - MYSQL_HOST=mydb
      - MYSQL_PORT=3306
      - MYSQL_USER=stella
      - MYSQL_PASSWORD=23322907
    ports:
      - "8001:8000"
    networks:
      - app-network
  mydb:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=taipei_attractions
      - MYSQL_ROOT_PASSWORD=23322907
      - MYSQL_USER=stella
      - MYSQL_PASSWORD=23322907
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "stella",
          "-p23322907",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./taipei_attractions.sql:/docker-entrypoint-initdb.d/taipei_attractions.sql
    restart: always
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
