name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Next Version
        id: version
        run: |
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            NEXT_TAG="v1.0.0"
          else
            COMMIT_MSG=$(git log -1 --pretty=%B)
            CURRENT_VERSION=$(echo $LATEST_TAG | sed 's/v//')
            MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
            MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
            PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
            
            if echo "$COMMIT_MSG" | grep -q "BREAKING CHANGE\|feat.*!:\|fix.*!:\|refactor.*!:"; then
              NEXT_TAG="v$((MAJOR + 1)).0.0"
            elif echo "$COMMIT_MSG" | grep -q "feat[[:space:]]*(.*):"; then  # 修正了這裡的正則表達式
              NEXT_TAG="v${MAJOR}.$((MINOR + 1)).0"
            else
              NEXT_TAG="v${MAJOR}.${MINOR}.$((PATCH + 1))"
            fi
          fi
          DATE=$(date +%Y%m%d)
          echo "VERSION=${NEXT_TAG}-${DATE}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          IMAGE=stellayou/taipei-day-trip
          docker build -t $IMAGE:${{ env.VERSION }} .
          docker push $IMAGE:${{ env.VERSION }}

      - name: Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull stellayou/taipei-day-trip:${{ env.VERSION }}

      - name: Debug Environment Variables
        run: |
          echo "Checking environment variables..."
          echo "ACCESS_TOKEN_EXPIRE_DAYS: ${{ vars.ACCESS_TOKEN_EXPIRE_DAYS }}"
          echo "ALGORITHM: ${{ vars.ALGORITHM }}"
          echo "MERCHANT_ID: ${{ vars.MERCHANT_ID }}"
          echo "MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}"
          echo "MYSQL_HOST: ${{ vars.MYSQL_HOST }}"
          echo "MYSQL_PORT: ${{ vars.MYSQL_PORT }}"
          echo "MYSQL_USER: ${{ vars.MYSQL_USER }}"
          echo "VERSION: ${{ env.VERSION }}"
                
          # 檢查 secrets 是否存在 (不會顯示實際值)
          echo "Checking secrets..."
          echo "MYSQL_PASSWORD exists: ${{ secrets.MYSQL_PASSWORD != '' }}"
          echo "SECRET_KEY exists: ${{ secrets.SECRET_KEY != '' }}"
          echo "PARTNER_KEY exists: ${{ secrets.PARTNER_KEY != '' }}"
          echo "EC2_HOST exists: ${{ secrets.EC2_HOST != '' }}"
          echo "EC2_SSH_KEY exists: ${{ secrets.EC2_SSH_KEY != '' }}"

      - name: Stop and Remove Existing Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop taipei-day-trip || true
            docker rm taipei-day-trip || true

      - name: Deploy New Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying new container..."
            docker run -d \
              --name taipei-day-trip \
              -p 8000:8000 \
              -e ACCESS_TOKEN_EXPIRE_DAYS="${{ vars.ACCESS_TOKEN_EXPIRE_DAYS }}" \
              -e ALGORITHM="${{ vars.ALGORITHM }}" \
              -e MERCHANT_ID="${{ vars.MERCHANT_ID }}" \
              -e MYSQL_DATABASE="${{ vars.MYSQL_DATABASE }}" \
              -e MYSQL_HOST="${{ vars.MYSQL_HOST }}" \
              -e MYSQL_PORT="${{ vars.MYSQL_PORT }}" \
              -e MYSQL_USER="${{ vars.MYSQL_USER }}" \
              -e MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
              -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
              -e TAPPAY_SANDBOX_URL="${{ vars.TAPPAY_SANDBOX_URL }}" \
              -e PARTNER_KEY="${{ secrets.PARTNER_KEY }}" \
              stellayou/taipei-day-trip:${{ env.VERSION }}
