name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Next Version
        id: version
        run: |
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            NEXT_TAG="v1.0.0"
          else
            COMMIT_MSG=$(git log -1 --pretty=%B)
            CURRENT_VERSION=$(echo $LATEST_TAG | sed 's/v//')
            MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
            MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
            PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
            
            if echo "$COMMIT_MSG" | grep -q "BREAKING CHANGE\|feat.*!:\|fix.*!:\|refactor.*!:"; then
              NEXT_TAG="v$((MAJOR + 1)).0.0"
            elif echo "$COMMIT_MSG" | grep -q "feat(.*):"; then
              NEXT_TAG="v${MAJOR}.$((MINOR + 1)).0"
            else
              NEXT_TAG="v${MAJOR}.${MINOR}.$((PATCH + 1))"
            fi
          fi
          DATE=$(date +%Y%m%d)
          echo "VERSION=${NEXT_TAG}-${DATE}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          IMAGE=stellayou/taipei-day-trip
          docker build -t $IMAGE:${{ env.VERSION }} .

      - name: Validate Docker Image Tag
        run: |
          if [[ ! "${{ env.VERSION }}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
            echo "Invalid version format: ${{ env.VERSION }}"
            exit 1
          fi

      - name: Push to Docker Hub
        run: |
          docker push $IMAGE:${{ env.VERSION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull stellayou/taipei-day-trip:${{ env.VERSION }}
            docker-compose down
            docker-compose up -d
