name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Version and Date
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          DATE=$(date +%Y%m%d)
          echo "VERSION=${VERSION}-${DATE}" >> $GITHUB_ENV

      - name: Build and Push
        run: |
          IMAGE=stellayou/taipei-day-trip
          docker build -t $IMAGE:${{ env.VERSION }} .
          docker push $IMAGE:${{ env.VERSION }}
